FROM node:lts as BUILD
WORKDIR /builder/
ADD . .
RUN npm config set strict-ssl false \
    && npm config set registry http://npm.inhuawei.com/ \    
    && npm install pnpm -g \   
    && pnpm i \
    && pnpm run build \
    && pnpm run docs:build

# 安装依赖 
FROM nginx:latest
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /builder/docs/.vitepress/dist /usr/share/nginx/html
EXPOSE 5174

