FROM node:lts as BUILD
WORKDIR /builder/
ADD . .
RUN npm config set strict-ssl false \
    && npm config set registry http://npm.inhuawei.com/ \    
    && npm i \
    && npm run docs:build

# 安装依赖 
FROM nginx:latest
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /builder/.vitepress/dist/ /usr/share/nginx/html
EXPOSE 5174

